### ISSUE TITLE
[Feature Request] combat marker on "next up" token too

### ISSUE THREAD

**Issue by tehguitarist** [ironmonk88/monks-combat-marker#3] opened 2023-03-04 21:17 UTC
Subject says it all really, a nice extra visual reminder than a token up might be nice. I suppose for GM's it could show the NPC's up next too (but not for players) and then for players, only friendlies will show up.

**Comment by ironmonk108** [comment] 2023-08-14 05:21
Closing this as duplicate of #5

**Closed as completed by ironmonk108** 2023-08-14 05:21 UTC
Labels: duplicate
